### PR TITLE
Removed email to as mandatory if cc or bcc are filled in the mail task

### LINKED ISSUE #2561: Flowable email task : Email to should not be mandatory if email cc or email bcc is provided
**Describe the bug**
We are using flowable email task. We have one of the requirement where we are allowing user to provide only bcc  options. 
How ever flowable is throwing error that email to is mandatory.

**Expected behavior**
Email to should not b mandatory if Email cc or Email bcc is provided.

### PR DESCRIPTION
**Pull request by 4gsim**
#### Check List:
* Unit tests: YES
* Documentation: NO

[Flowable email task : Email to should not be mandatory if email cc or email bcc is provided](https://github.com/flowable/flowable-engine/issues/2561)

Fixes #2561

### CODE REVIEW

File: modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/ExternalInvocationTaskValidator.java [hunk 1]
```diff
@@ -49,7 +55,7 @@ protected void validateFieldDeclarationsForEmail(org.flowable.bpmn.model.Process
             }
         }
 
-        if (!toDefined) {
+        if (!recipientDefined) {
```
Comment (filiphr) [inline modules/flowable-process-validation/src/main/java/org/flowable/validation/validator/impl/ExternalInvocationTaskValidator.java:58]: Can we add some tests for this validation as well? e.g. a mail task with only `cc`, another one with only `bcc`

**Review by filiphr — CHANGES_REQUESTED** [review]
Thanks for the PR @4gsim. It looks great. 

Can we please do the same changes in `MailActivityBehavior` in the CMMN Engine as well?

In addition to that can we also add a test without a `to` and with `cc`. The test you added is good, but it only tests for `bcc`. Just to cover all our bases 😄

File: modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailSendTaskTest.java [hunk 2]
```diff
@@ -146,6 +146,54 @@ public void testCcAndBccWithForceTo() throws Exception {
...
+    }
+
+    @Test
+    @Deployment
+    public void testOnlyCcAddress() throws Exception {
+        runtimeService.startProcessInstanceByKey("onlyCcAddress");
+
+        List<WiserMessage> messages = wiser.getMessages();
+        assertEmailSend(messages.get(0), false, "Hello world", "This is the content", "flowable@localhost", Collections.emptyList(),
+                Collections.emptyList());
```
Comment (filiphr) [inline modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailSendTaskTest.java:172]: `assertEmailSend` can verify the `cc` and `to` addresses specifically lets do:

```suggestion
        assertEmailSend(messages.get(0), false, "Hello world", "This is the content", "flowable@localhost", Collections.emptyList(),
                "mispiggy@activiti.org");
```

File: modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailSendTaskTest.java [hunk 3]
```diff
@@ -146,6 +146,54 @@ public void testCcAndBccWithForceTo() throws Exception {
...
+    }
+
+    @Test
+    @Deployment
+    public void testOnlyToAddress() throws Exception {
+        runtimeService.startProcessInstanceByKey("onlyToAddress");
+
+        List<WiserMessage> messages = wiser.getMessages();
+        assertEmailSend(messages.get(0), false, "Hello world", "This is the content", "flowable@localhost", Collections.emptyList(),
+                Collections.emptyList());
```
Comment (filiphr) [inline modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailSendTaskTest.java:188]: `assertEmailSend` can verify the `to` address specifically. Lets do:

```suggestion
        assertEmailSend(messages.get(0), false, "Hello world", "This is the content", "flowable@localhost", "mispiggy@activiti.org",
                Collections.emptyList());
```

**Review by filiphr — COMMENTED** [review]
Thanks a lot for your changes @4gsim. 

I've proposed 2 small changes, let me know if you are OK with them. They are also applicable for the `EmailServiceTaskTest`.

File: modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailSendTaskTest.java (hunk 2 above)
Comment (4gsim) [reply modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailSendTaskTest.java]: Done

File: modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailSendTaskTest.java (hunk 3 above)
Comment (4gsim) [reply modules/flowable-engine/src/test/java/org/flowable/engine/test/bpmn/mail/EmailSendTaskTest.java]: Done

**Comment by filiphr** [comment]
Thanks a lot for the changes @4gsim. We've merged this.
